### PR TITLE
Parameter intelligence

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Parameter restrictions are generated automatically based on `.getParameters()` in each command, rather than manually specifying in render.

### CODE REVIEW

**Comment by faulda** [comment]
So does this mean no more requireLength* methods in render?

**Comment by JoshuaKGoldberg** [comment]
Precisely.

**Comment by faulda** [comment]
Any other notable changes to command implementations?

**Comment by JoshuaKGoldberg** [comment]
None that I can think of. As long as you fill out the `getParameters` method, parameter checking should be automatic.

**Pull request merged**
